exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('content').del()
    .then(function () {
      // Inserts seed entries
      return knex('content').insert([
        { id: 1, category_id: 1, english: 'baby', Niuean: 'tama muke / mukemuke' },
        { id: 2, category_id: 1, english: 'child', Niuean: 'tama' },
        { id: 3, category_id: 1, english: 'sibling / cousin', Niuean: 'lafu' },
        { id: 4, category_id: 1, english: 'younger sibling', Niuean: 'tehina' },
        { id: 5, category_id: 1, english: 'older sibling', Niuean: 'taokete' },
        { id: 6, category_id: 1, english: 'girl', Niuean: 'tama fifine' },
        { id: 7, category_id: 1, english: 'boy', Niuean: 'tama taane' },
        { id: 8, category_id: 1, english: 'grandchild', Niuean: 'pulapulaola / mokopuna' },
        { id: 9, category_id: 1, english: 'niece', Niuean: 'tamafifine he taokete' },
        { id: 10, category_id: 1, english: 'nephew', Niuean: 'tama taane he taokete' },
        { id: 11, category_id: 1, english: 'sister (of male sibling)', Niuean: 'mahakitaga' },
        { id: 12, category_id: 1, english: 'brother (of female sibling)', Niuean: 'tugaane' },
        { id: 13, category_id: 1, english: 'parent', Niuean: 'faimatua' },
        { id: 14, category_id: 1, english: 'father', Niuean: 'matua taane' },
        { id: 15, category_id: 1, english: 'mother', Niuean: 'matua fifine' },
        { id: 16, category_id: 2, english: 'coconut crab', Niuean: 'uga' },
        { id: 17, category_id: 2, english: 'orange', Niuean: 'fua moli' },
        { id: 18, category_id: 2, english: 'raw fish', Niuean: 'ota' },
        { id: 19, category_id: 2, english: 'lemon', Niuean: 'fua tipolo' },
        { id: 20, category_id: 2, english: 'watermelon', Niuean: 'fua meleni' },
        { id: 21, category_id: 2, english: 'passionfruit', Niuean: 'fua vine' },
        { id: 22, category_id: 2, english: 'coconut superpower loaf', Niuean: 'pitako' },
        { id: 23, category_id: 2, english: 'cake', Niuean: 'keke' },
        { id: 24, category_id: 2, english: 'mango', Niuean: 'fua mago' },
        { id: 25, category_id: 2, english: 'baked taro and pawpaw dish', Niuean: 'takihi' },
        { id: 26, category_id: 2, english: 'sausage', Niuean: 'tosisi' },
        { id: 27, category_id: 2, english: 'coconut', Niuean: 'fua niu' },
        { id: 28, category_id: 2, english: 'cabbage', Niuean: 'kapisi' },
        { id: 29, category_id: 2, english: 'cheese', Niuean: 'siisi' },
        { id: 30, category_id: 2, english: 'lollies', Niuean: 'lole' },
        { id: 31, category_id: 2, english: 'egg', Niuean: 'fua' },
        { id: 32, category_id: 2, english: 'kumara', Niuean: 'timala' },
        { id: 33, category_id: 2, english: 'coffee', Niuean: 'kofe' },
        { id: 34, category_id: 2, english: 'tea', Niuean: 'ti' },
        { id: 35, category_id: 2, english: 'cocoa', Niuean: 'koko' },
        { id: 36, category_id: 2, english: 'banana', Niuean: 'futi' },
        { id: 37, category_id: 2, english: 'apple', Niuean: 'fua apala' },
        { id: 38, category_id: 3, english: 'hello', Niuean: 'fakaalofa atu' },
        { id: 39, category_id: 3, english: 'greetings', Niuean: 'fakaalofa lahi atu' },
        { id: 40, category_id: 3, english: 'greetings to you both', Niuean: 'fakaalofa lahi atu kia mua' },
        { id: 41, category_id: 3, english: 'greetings to you all', Niuean: 'fakaalofa lahi atu kia mutolu oti' },
        { id: 42, category_id: 3, english: 'precious greetings to you', Niuean: 'fakaalofa hofihofi atu' },
        { id: 43, category_id: 3, english: 'good morning', Niuean: 'monuina e pogipogi' },
        { id: 44, category_id: 3, english: 'have a nice day', Niuean: 'monuina e aho' },
        { id: 45, category_id: 3, english: 'good evening', Niuean: 'monuina e afiafi' },
        { id: 46, category_id: 3, english: 'good night', Niuean: 'monuina e po' },
        { id: 47, category_id: 3, english: 'goodbye', Niuean: 'koe kia' },
        { id: 48, category_id: 4, english: 'zero', Niuean: 'nakai' },
        { id: 49, category_id: 4, english: 'one', Niuean: 'taha' },
        { id: 50, category_id: 4, english: 'two', Niuean: 'ua' },
        { id: 51, category_id: 4, english: 'three', Niuean: 'tolu' },
        { id: 52, category_id: 4, english: 'four', Niuean: 'fa' },
        { id: 53, category_id: 4, english: 'five', Niuean: 'lima' },
        { id: 54, category_id: 4, english: 'six', Niuean: 'ono' },
        { id: 55, category_id: 4, english: 'seven', Niuean: 'fitu' },
        { id: 56, category_id: 4, english: 'eight', Niuean: 'valu' },
        { id: 57, category_id: 4, english: 'nine', Niuean: 'hiva' },
        { id: 58, category_id: 4, english: 'ten', Niuean: 'hogofulu' },
        { id: 59, category_id: 4, english: 'eleven', Niuean: 'hogofulu ma taha' },
        { id: 60, category_id: 4, english: 'twelve', Niuean: 'hogofulu ma ua' },
        { id: 61, category_id: 4, english: 'thirteen', Niuean: 'hogofulu ma tolu' },
        { id: 62, category_id: 4, english: 'fourteen', Niuean: 'hogofulu ma fa' },
        { id: 63, category_id: 4, english: 'fifteen', Niuean: 'hogofulu ma lima' },
        { id: 64, category_id: 4, english: 'sixteen', Niuean: 'hogofulu ma ono' },
        { id: 65, category_id: 4, english: 'seventeen', Niuean: 'hogofulu ma fitu' },
        { id: 66, category_id: 4, english: 'eighteen', Niuean: 'hogofulu ma valu' },
        { id: 67, category_id: 4, english: 'nineteen', Niuean: 'hogofulu ma hiva' },
        { id: 68, category_id: 4, english: 'twenty', Niuean: 'ua hogofulu' },
        { id: 69, category_id: 5, english: 'monday', Niuean: 'aho gofua' },
        { id: 70, category_id: 5, english: 'tuesday', Niuean: 'aho ua' },
        { id: 71, category_id: 5, english: 'wednesday', Niuean: 'aho lotu' },
        { id: 72, category_id: 5, english: 'thursday', Niuean: 'aho tuloto' },
        { id: 73, category_id: 5, english: 'friday', Niuean: 'aho falaile' },
        { id: 74, category_id: 5, english: 'saturday', Niuean: 'aho faiumu' },
        { id: 75, category_id: 5, english: 'sunday', Niuean: 'aho tapu' },
        { id: 76, category_id: 5, english: 'january', Niuean: 'ianuali' },
        { id: 77, category_id: 5, english: 'february', Niuean: 'fepuali' },
        { id: 78, category_id: 5, english: 'march', Niuean: 'masi' },
        { id: 79, category_id: 5, english: 'april', Niuean: 'apelila' },
        { id: 80, category_id: 5, english: 'may', Niuean: 'me' },
        { id: 81, category_id: 5, english: 'june', Niuean: 'iuni' },
        { id: 82, category_id: 5, english: 'july', Niuean: 'iulai' },
        { id: 83, category_id: 5, english: 'august', Niuean: 'aukuso' },
        { id: 84, category_id: 5, english: 'september', Niuean: 'sepetema' },
        { id: 85, category_id: 5, english: 'october', Niuean: 'oketopa' },
        { id: 86, category_id: 5, english: 'november', Niuean: 'novema' },
        { id: 87, category_id: 5, english: 'december', Niuean: 'tesemo' },
        { id: 88, category_id: 6, english: 'mouth', Niuean: 'gutu' },
        { id: 89, category_id: 6, english: 'nose', Niuean: 'ihu' },
        { id: 90, category_id: 6, english: 'eye', Niuean: 'mata' },
        { id: 91, category_id: 6, english: 'toe', Niuean: 'matahui' },
        { id: 92, category_id: 6, english: 'knee', Niuean: 'matatuli' },
        { id: 93, category_id: 6, english: 'ear', Niuean: 'teliga' },
        { id: 94, category_id: 6, english: 'shoulder', Niuean: 'tukeua' },
        { id: 95, category_id: 6, english: 'head', Niuean: 'ulu' },
        { id: 96, category_id: 6, english: 'arm / hand', Niuean: 'lima' },
        { id: 97, category_id: 6, english: 'thirsty', Niuean: 'fia inu' },
        { id: 98, category_id: 6, english: 'hungry', Niuean: 'hoge' },
        { id: 99, category_id: 6, english: 'hot / warm', Niuean: 'mafana' },
        { id: 100, category_id: 6, english: 'excited', Niuean: 'mainiini' },
        { id: 101, category_id: 6, english: 'tired', Niuean: 'mategugu' },
        { id: 102, category_id: 6, english: 'starving', Niuean: 'matehoge' },
        { id: 103, category_id: 6, english: 'sad / cold', Niuean: 'momoko' },
        { id: 104, category_id: 6, english: 'sick', Niuean: 'tatalu' },
        { id: 105, category_id: 6, english: 'down / worried', Niuean: 'tupetupe' }

      ])
    })
}
